# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-04-18 19:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_remove_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='poll_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
