# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-05-07 01:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_auto_20180418_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='end_date',
            field=models.DateField(default=datetime.date(2018, 5, 7)),
        ),
    ]
